title: Deep Dive Literature Review of Diffusion Models
description: Thes pages are attempting to give an overview of the Diffusion Model literature in the past decade or so.
show_downloads: false

author:
  name: Zsolt Pajor-Gyulai
  email: pgyzs1@gmail.com
  github: Moosquibe

theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..4
